#################################################################################
#                               OneBranch Pipelines                             #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger: none  # https://aka.ms/obpipelines/triggers

# global parameteres are configured here and show up in AzDO UI in build queue time. Required for MSBuild and .NET.
# learn more at https://aka.ms/obpipelines/parameters
# parameters:
# - name: 'debug'
#  displayName: 'Enable debug output'
#  type: boolean
#  default: false

variables:
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)]  # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning

  ### Specify container image and other global variables in this section! ###
  # https://eng.ms/docs/products/onebranch/build/containerbasedworkflow#minimal-required-yaml | This doesn't work for me: https://aka.ms/obpipelines/variables
  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2022/vse2022:latest' # for Windows jobs https://aka.ms/obpipelines/containers
  LinuxContainerImage: 'mcr.microsoft.com/onebranch/cbl-mariner/build:2.0' # for Linux jobs

resources:
  repositories:
  - repository: templates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main
  - repository: ServiceProfiler # my team templates
    type: git
    name: OnlineServices/ServiceProfiler # project and repo name where to find templates
    ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates  # https://aka.ms/obpipelines/templates
  parameters:
    cloudvault:  # https://aka.ms/obpipelines/cloudvault
      enabled: false
      ### Linux Pipelines can uncomment the following to run CloudVault update as a seperate stage. ###
      # runmode: stage
      # dependsOn: linux_build
      # artifacts:
      #  - drop_linux_stage_linux_job
    git:
      submodules: true
    globalSdl:  # https://aka.ms/obpipelines/sdl
      perStage:
        sdl_sources:
          checkout_all_repos: true
      tsa:
        enabled: false  # onebranch publish all SDL results to TSA. If TSA is disabled all SDL tools will forced into 'break' build mode.
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      binskim:
        break: true  # always break the build on binskim issues in addition to TSA upload
      policheck:
        break: true  # always break the build on policheck issues. You can disable it by setting to 'false'
      # suppression:
      #   suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress

    stages:
    # The file contains an example HelloWorld script. For more info and examples, see the links below
    # https://aka.ms/obpipelines/containerbuildexamples
    # https://aka.ms/obpipelines/containerprojectypes
    - stage: build
      displayName: Build the Solution
      jobs:
      - job: sampleJob
        pool:
          type: linux
        variables:
          ob_outputDirectory: '$(REPOROOT)\out'  # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts
        steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '8.x'

        - task: NuGetCommand@2
          inputs:
            command: 'restore'
            restoreSolution: '$(Build.SourcesDirectory)/src/Azure.Monitor.OpenTelemetry.Profiler.sln'
            feedsToUse: 'select'
            vstsFeed: 'devdiv/DiagnosticServices'
            includeNuGetOrg: false
        
## For info and instructions on CloudTest, see https://aka.ms/obpipelines/cloudtest
