version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords: 
    - "artifactkinds"
    - "browsable"
    - "etl"
    - "etlupload"
    - "gettoken"
    - "nettrace"
    - "profileragent"
    - "snapshotagent"
    - "spstampcookie"
    - "stampid"
import: []
